# Brief learning tips (max ~2 short sentences) keyed by vocabulary word.
# Prefer root/etymology breakdowns that help learners derive meaning.

EXPLANATIONS = {
    "inchoate": 'From Latin inchoare, "to begin." Think of something only just started and still formless.',
    "pervious": 'From Latin per (through) + via (way). Something pervious lets things pass through it.',
    "evanescent": 'From Latin evanescere, "to vanish." Evanescent things fade away almost as soon as they appear.',
    "fastidious": 'From Latin fastidium, "loathing" or disgust. A fastidious person is hard to please about details.',
    "incipient": 'From Latin incipere, "to begin" (in + capere, "take hold"). It marks the very start of something.',
    "gregarious": 'From Latin grex, "flock." Gregarious people like being in a group, like animals in a herd.',
    "laconic": 'From Laconia, home of the Spartans, famous for terse speech. Laconic means brief to the point of bluntness.',
    "taciturn": 'From Latin tacitus, "silent." A taciturn person habitually says little.',
    "capricious": 'Linked to Italian capriccio (whim), from capra, "goat." Like a goat\'s sudden leaps, moods change unpredictably.',
    "munificent": 'From Latin munus (gift) + facere (to make). Literally "gift-making" — extremely generous.',
    "parsimonious": 'From Latin parcere, "to spare" or be thrifty. It means stingy with money or resources.',
    "sanguine": 'From Latin sanguis, "blood." Medieval medicine linked a bloody temperament with cheerful optimism.',
    "amenable": 'From French amener, "to lead to." Amenable people can be led or persuaded.',
    "pragmatic": 'From Greek pragma, "deed" or practical matter. Focus on what works in practice, not pure theory.',
    "verbose": 'From Latin verbum, "word." Verbose speech uses too many words.',
    "obstinate": 'From Latin obstinare, "to persist." An obstinate person stubbornly sticks to a course.',
    "ephemeral": 'From Greek ephemeros, "lasting a day" (epi + hemera, day). It means short-lived.',
    "ubiquitous": 'From Latin ubique, "everywhere." If something is ubiquitous, you find it all over.',
    "benevolent": 'From Latin bene (well) + volens (wishing). A benevolent person wishes others well.',
    "garrulous": 'From Latin garrulus, "talkative," from garrire, "to chatter." It means excessively chatty.',
    "prolix": 'From Latin prolixus, "poured forth" or extended. Prolix writing is tediously long-winded.',
    "esoteric": 'From Greek esoterikos, "inner." Esoteric knowledge is for a small inner circle of specialists.',
    "mendacious": 'From Latin mendax, "lying." Mendacious means dishonest or untruthful.',
    "circumspect": 'From Latin circum (around) + specere (to look). Look carefully around before you act.',
    "quixotic": 'From Don Quixote, Cervantes\' idealistic knight. It means noble but hopelessly impractical.',
    "meretricious": 'From Latin meretrix, "prostitute." It means flashy and alluring on the surface but hollow.',
    "recondite": 'From Latin recondere, "to hide away." Recondite topics are obscure and little known.',
    "abstruse": 'From Latin abstrudere, "to thrust away" or conceal. Abstruse ideas are hard to grasp.',
    "perspicacious": 'From Latin perspicax, "seeing through" (per + specere). Keen insight that sees through things.',
    "lugubrious": 'From Latin lugere, "to mourn." Lugubrious means exaggeratedly mournful or gloomy.',
    "petulant": 'From Latin petere, "to aim at" or attack. Petulant behaviour is peevish and sulky over small things.',
    "obstreperous": 'From Latin obstrepere, "to make a noise against." Noisy, unruly resistance to control.',
    "supercilious": 'From Latin supercilium, "eyebrow." Raising the eyebrow — haughty, looking down on others.',
    "pusillanimous": 'From Latin pusillus (very small) + animus (spirit). Literally "tiny-spirited" — cowardly.',
    "magnanimous": 'From Latin magnus (great) + animus (spirit). Great-souled generosity, especially in forgiveness.',
    "intransigent": 'From Latin in- (not) + transigere (to come to an agreement). Unwilling to compromise.',
    "recalcitrant": 'From Latin recalcitare, "to kick back" (like a stubborn mule). Stubbornly uncooperative.',
    "erudite": 'From Latin erudire, "to instruct" (e- + rudis, rough/untrained). Learned through study.',
    "ineffable": 'From Latin in- (not) + effabilis (speakable). Too great or extreme to put into words.',
    "insouciant": 'From French in- (not) + souci (care). Carefree — casually unconcerned.',
    "querulous": 'From Latin queri, "to complain." Querulous means given to whining complaints.',
    "truculent": 'From Latin trux, "fierce." Truculent people are aggressively ready to fight or argue.',
    "jejune": 'From Latin jejunus, "fasting" or empty. Jejune ideas feel thin, naive, and unnourishing.',
    "scintillating": 'From Latin scintilla, "spark." Scintillating talk sparkles with wit and liveliness.',
    "obsequious": 'From Latin obsequi, "to comply." Excessively eager to please — servile flattery.',
    "perfunctory": 'From Latin perfungi, "to get through" a duty. Done with minimal care, just to finish it.',
    "assiduous": 'From Latin assidere, "to sit by" a task. Persistent, careful effort over time.',
    "voracious": 'From Latin vorare, "to devour." Voracious means insatiably hungry for food or knowledge.',
    "reticent": 'From Latin reticere, "to keep silent." Reticent people hold back their thoughts and feelings.',
    "pugnacious": 'From Latin pugnare, "to fight" (pugnus, fist). Eager to quarrel or fight.',
    "inimical": 'From Latin inimicus, "enemy" (in- + amicus, friend). Hostile or harmful to something.',
    "vicarious": 'From Latin vicarius, "substitute." Experienced through someone else rather than directly.',
    "perfidious": 'From Latin per (through/against) + fides (faith). Literally breaking faith — treacherous.',
    "dilatory": 'From Latin dilatus, "deferred." Dilatory tactics are meant to cause delay.',
    "multifarious": 'From Latin multi (many) + farius (kinds). Made up of many different kinds.',
    "sesquipedalian": 'From Latin sesqui (one and a half) + pes (foot). "A foot and a half long" — fond of long words.',
    "impetuous": 'From Latin impetere, "to attack." Impetuous acts rush forward without careful thought.',
    "obfuscate": 'From Latin obfuscare, "to darken." To obfuscate is to make something harder to understand.',
    "palimpsest": 'From Greek palimpsēstos, "scraped again." A reused manuscript where older writing still shows through.',
    "sycophant": 'From Greek sykophantēs (originally an informer). Now means a self-serving flatterer.',
    "amorphous": 'From Greek a- (without) + morphē (shape). Without a clear shape or structure.',
    "affable": 'From Latin ad- (to) + fari (to speak). Easy and friendly to speak with.',
    "alacrity": 'From Latin alacer, "brisk" or lively. Cheerful readiness and prompt eagerness.',
    "auspicious": 'From Latin auspex, a bird-diviner reading omens. Favourable signs of future success.',
    "bellicose": 'From Latin bellum, "war." Bellicose means warlike or eager to fight.',
    "capacious": 'From Latin capax, "able to hold" (capere, to take). Spacious and able to hold a lot.',
    "complaisant": 'From French complaire, "to please." Willing to go along with others\' wishes.',
    "credulous": 'From Latin credere, "to believe." Too ready to believe — easily deceived.',
    "decorous": 'From Latin decorus, "seemly." Proper, polite, and in good taste.',
    "diffident": 'From Latin dis- (apart) + fidere (to trust). Lacking self-trust — shy and hesitant.',
    "dichotomy": 'From Greek dicha (in two) + temnein (to cut). A division into two opposing parts.',
    "ebullient": 'From Latin ebullire, "to boil over." Overflowing with cheerful energy.',
    "eclectic": 'From Greek eklegein, "to select." Choosing the best ideas from many different sources.',
    "equanimous": 'From Latin aequus (even) + animus (mind). An even mind — calm under stress.',
    "equivocal": 'From Latin aequus (equal) + vox (voice). Two equal "voices" of meaning — ambiguous.',
    "exigent": 'From Latin exigere, "to demand." Exigent needs demand immediate attention.',
    "facetious": 'From Latin facetia, "jest." Treating serious matters with inappropriate humour.',
    "fallacious": 'From Latin fallacia, "deception." Based on a false or misleading argument.',
    "fatuous": 'From Latin fatuus, "foolish." Silly and empty of real intelligence.',
    "florid": 'From Latin flos, "flower." Flowery — flushed in complexion or ornate in style.',
    "fortuitous": 'From Latin fors, "chance." Happening by chance (often luckily), not by design.',
    "fractious": 'From Latin frangere, "to break." Irritable and hard to manage — ready to "break" into quarrel.',
    "galvanize": 'Named after Luigi Galvani\'s electricity experiments. To shock someone into sudden action.',
    "grandiose": 'From Italian grandioso, from Latin grandis, "great." Impressive in scale, often overly so.',
    "haphazard": 'From "hap" (chance, as in happen) + hazard. Done by chance, without a plan.',
    "hubris": 'From Greek hybris, "wanton pride." Excessive arrogance that invites a fall.',
    "idyllic": 'From Greek eidyllion, a short pastoral poem. Peacefully picturesque, like a perfect scene.',
    "impertinent": 'From Latin in- (not) + pertinere (to belong). Not belonging — rudely out of place.',
    "indolent": 'From Latin in- (not) + dolere (to feel pain/effort). Avoiding effort — habitually lazy.',
    "ingenuous": 'From Latin ingenuus, "freeborn" and frank. Open, innocent, and candid.',
    "inordinate": 'From Latin in- (not) + ordinatus (ordered). Beyond normal limits — excessive.',
    "insidious": 'From Latin insidiae, "ambush." Harm that creeps up subtly, like a trap.',
    "inveterate": 'From Latin in- + vetus (old). Long-established and deep-rooted, like an old habit.',
    "irascible": 'From Latin ira, "anger." Quick to become angry.',
    "jocular": 'From Latin jocus, "joke." Characterised by joking and humour.',
    "languid": 'From Latin languere, "to be faint." Weak, sluggish, and lacking energy.',
    "litigious": 'From Latin lis (lawsuit) + agere (to drive). Too ready to settle disputes in court.',
    "malleable": 'From Latin malleus, "hammer." Able to be hammered into shape — easily influenced.',
    "mitigate": 'From Latin mitis (soft) + agere (to make). To make something milder or less severe.',
    "morose": 'From Latin morosus, "peevish." Sullen and ill-tempered.',
    "nascent": 'From Latin nasci, "to be born." Just coming into being — beginning to develop.',
    "nebulous": 'From Latin nebula, "cloud" or mist. Hazy, vague, and ill-defined.',
    "nugatory": 'From Latin nugae, "trifles" or jokes. Of no real value or importance.',
    "officious": 'From Latin officium, "duty" (in a busybody sense). Meddlesomely assertive about "helping."',
    "opulent": 'From Latin opes, "wealth." Ostentatiously rich and luxurious.',
    "pellucid": 'From Latin per (through) + lucere (to shine). So clear that light (and meaning) shines through.',
    "placid": 'From Latin placere, "to please" or calm. Calm, peaceful, and hard to upset.',
    "precocious": 'From Latin prae (before) + coquere (to cook/ripen). "Ripened early" — advanced for one\'s age.',
    "acerbic": 'From Latin acerbus, "bitter" or harsh. Sharp and cutting in tone.',
    "anodyne": 'From Greek an- (without) + odynē (pain). Originally a painkiller — now "harmlessly bland."',
    "antediluvian": 'From Latin ante (before) + diluvium (flood). Literally "before the flood" — ridiculously outdated.',
    "atrabilious": 'From Latin atra bilis, "black bile." Old medicine linked black bile to gloomy, irritable moods.',
    "audacious": 'From Latin audax, "bold" (audere, to dare). Daring enough to take bold risks.',
    "baleful": 'From Old English bealu, "evil" or harm. Threatening harm or disaster.',
    "bibulous": 'From Latin bibere, "to drink." Excessively fond of drinking alcohol.',
    "bombastic": 'From bombast, padding used to stuff clothes. Language puffed up with empty grandeur.',
    "captious": 'From Latin capere, "to seize" or catch. Eager to catch people out with petty objections.',
    "choleric": 'From Greek cholē, "bile." Old humour theory linked yellow bile to a quick temper.',
    "corpulent": 'From Latin corpus, "body." Having a large, bulky body.',
    "deleterious": 'From Greek dēlētērios, "destructive." Causing harm or damage.',
    "desultory": 'From Latin desultor, a circus rider who leaps between horses. Jumping randomly, without a plan.',
    "diaphanous": 'From Greek dia (through) + phainein (to show). So light and sheer that you can see through it.',
    "didactic": 'From Greek didaskein, "to teach." Intended to instruct, often in a moral way.',
    "disingenuous": 'From dis- (not) + ingenuous (frank). Not candid — pretending ignorance or innocence.',
    "egregious": 'From Latin e grege, "out of the flock." Standing out — now for outstandingly bad faults.',
    "enervating": 'From Latin enervare, "to cut the sinews" (e- + nervus). Draining strength and energy.',
    "epicurean": 'From Epicurus, the Greek philosopher. Devoted to refined pleasure, especially fine food.',
    "execrable": 'From Latin exsecrari, "to curse." So bad as to deserve cursing — detestable.',
    "exiguous": 'From Latin exiguus, "scanty." Extremely small in amount.',
    "expeditious": 'From Latin expedire, "to free the feet" for travel. Done with speed and efficiency.',
    "extemporaneous": 'From Latin ex tempore, "out of the moment." Spoken or done without preparation.',
    "feckless": 'From Scots feck (effect, value) + -less. Lacking effectiveness — irresponsibly weak.',
    "fecund": 'From Latin fecundus, "fruitful." Producing many offspring, ideas, or results.',
    "furtive": 'From Latin fur, "thief." Secretive, as if stealing away to avoid notice.',
    "grandiloquent": 'From Latin grandis (grand) + loqui (to speak). Pompous, lofty speech.',
    "heuristic": 'From Greek heuriskein, "to find." A practical method that helps you discover answers by trying.',
    "iconoclastic": 'From Greek eikōn (image) + klastēs (breaker). Attacking cherished images, beliefs, or institutions.',
    "impecunious": 'From Latin in- (not) + pecunia (money). Having little or no money.',
    "imperious": 'From Latin imperium, "command." Domineering, as if entitled to give orders.',
    "imperturbable": 'From Latin in- (not) + perturbare (to disturb). Unable to be upset — calmly unshakable.',
    "impervious": 'From Latin in- (not) + pervius (passable). Nothing gets through — sealed against fluid or influence.',
    "indefatigable": 'From Latin in- (not) + defatigare (to tire out). Unable to be wearied — tirelessly persistent.',
    "indomitable": 'From Latin in- (not) + domitare (to tame). Impossible to subdue or defeat.',
    "inscrutable": 'From Latin in- (not) + scrutari (to search). Impossible to "search into" — enigmatic.',
    "insipid": 'From Latin in- (not) + sapidus (tasty). Without flavour — dull and uninteresting.',
    "intrepid": 'From Latin in- (not) + trepidus (alarmed). Fearless and boldly adventurous.',
    "invidious": 'From Latin invidia, "envy." Likely to cause resentment or unfair comparison.',
    "lachrymose": 'From Latin lacrima, "tear." Tearful or given to weeping.',
    "liminal": 'From Latin limen, "threshold." At a boundary or transitional threshold.',
    "luculent": 'From Latin lux, "light." Brightly clear — lucid and easy to follow.',
    "machiavellian": 'From Niccolò Machiavelli, author of The Prince. Cunning and scheming in pursuit of power.',
    "mellifluous": 'From Latin mel (honey) + fluere (to flow). Sweet and smoothly flowing, especially sound.',
    "mordant": 'From Latin mordere, "to bite." Sharply biting humour or criticism.',
    "nefarious": 'From Latin nefas, "crime" or wrong. Wickedly criminal or villainous.',
    "obdurate": 'From Latin ob- + durus (hard). Hardened against persuasion — stubbornly unyielding.',
    "oleaginous": 'From Latin oleum, "oil." Oily — unpleasantly smooth and flattering.',
    "ostensible": 'From Latin ostendere, "to show." The outward, stated reason — not necessarily the real one.',
    "pejorative": 'From Latin pejor, "worse." Expressing a worse, contemptuous sense of a word.',
    "penurious": 'From Latin penuria, "want" or scarcity. Extremely poor, or stingily tight with money.',
    "pernicious": 'From Latin pernicies, "destruction." Gradually destructive and harmful.',
    "perspicuous": 'From Latin per (through) + specere (to see). Clear enough to see through — easy to understand.',
    "phlegmatic": 'From Greek phlegma, "phlegm." Old humour theory linked phlegm to a calm, unemotional temperament.',
    "platitudinous": 'From platitude (a flat, trite remark), from French plat, "flat." Full of dull, obvious clichés.',
    "approbation": 'From Latin ad- (to) + probare (to test/approve). Formal approval or praise.',
    "catalyst": 'From Greek kata (down) + lyein (to loosen). In chemistry it speeds a reaction — in life, it sparks change.',
    "conundrum": 'Origin uncertain (perhaps a university joke-word). A puzzling problem or riddle.',
    "epiphany": 'From Greek epiphaneia, "manifestation" or appearance. A sudden moment of revelation.',
    "harangue": 'From Old French harangue, a public address. A long, aggressive speech or tirade.',
    "lacuna": 'From Latin lacuna, "pool" or hole. A gap or missing portion in a text or sequence.',
    "nadir": 'From Arabic nazīr, "opposite" (the sky point opposite the zenith). The lowest point.',
    "nemesis": 'From Greek Nemesis, goddess of retribution. A source of downfall — or a long-standing rival.',
    "panacea": 'From Greek pan (all) + akos (cure). A supposed cure for all problems.',
    "tirade": 'From French tirade, a long speech. An extended angry outburst of criticism.',
    "abscond": 'From Latin abs (away) + condere (to hide). To leave secretly and hide from justice or custody.',
    "adumbrate": 'From Latin ad- + umbra (shadow). To sketch in outline or foreshadow faintly, like a shadow.',
    "denigrate": 'From Latin de- + nigrare (to blacken). To blacken someone\'s reputation unfairly.',
    "equivocate": 'From Latin aequus (equal) + vox (voice). To speak with "equal voices" — deliberately ambiguous.',
    "eschew": 'From Old French eschiver, "to avoid." To deliberately abstain from or steer clear of something.',
    "impugn": 'From Latin in- + pugnare (to fight). To attack the truth or honesty of a claim.',
    "prevaricate": 'From Latin praevaricari, "to walk crookedly." To speak evasively and dodge the truth.',
}


def validate_explanations(words):
    missing = [w for w in words if w not in EXPLANATIONS]
    extra = [w for w in EXPLANATIONS if w not in set(words)]
    long = [
        (w, EXPLANATIONS[w])
        for w in words
        if w in EXPLANATIONS and EXPLANATIONS[w].count(".") > 2
    ]
    return missing, extra, long
