# Learning tips for verb/noun POS-balance entries.
EXPLANATIONS_VN = {
    'abate': 'From Old French abattre, "to beat down." Think of intensity being beaten down until it fades.',
    'abjure': 'From Latin abjurare, "to swear away." Solemnly renounce a belief or claim.',
    'abrogate': 'From Latin abrogare, "to repeal." Cancel a law or formal agreement.',
    'accrete': 'From Latin accrescere, "to grow." Build up by gradual addition of layers.',
    'acrimony': 'From Latin acer, "sharp." Bitterness in speech or feeling.',
    'adjudicate': 'From Latin adjudicare, "to award by judgment." Decide a dispute formally.',
    'admonish': 'From Latin admonere, "to warn" (ad + monere). A firm warning about behaviour.',
    'adulterate': 'From Latin adulterare, "to corrupt." Spoil purity by adding something inferior.',
    'allude': 'From Latin alludere, "to play with" or refer lightly. An allusion hints without stating fully.',
    'altruism': 'From Latin alter, "other" (via French). Selfless concern for others\' welfare.',
    'ambivalence': 'From Latin ambi (both) + valentia (strength). Mixed feelings pulling both ways.',
    'ameliorate': 'From Latin melior, "better." To ameliorate is to make a bad situation better.',
    'anathema': 'From Greek anathema, "something devoted (to evil)." A detested thing under ban.',
    'anomaly': 'From Greek anomalos, "uneven." Something that does not fit the usual pattern.',
    'anomie': 'From Greek a- (without) + nomos (law). Breakdown of social or ethical norms.',
    'antipathy': 'From Greek anti (against) + pathos (feeling). A deep-seated dislike.',
    'apathy': 'From Greek a- (without) + pathos (feeling). Lack of interest or concern.',
    'aphorism': 'From Greek aphorizein, "to define." A concise statement of a general truth.',
    'apotheosis': 'From Greek apo + theos, "make a god." The highest ideal form of something.',
    'appease': 'From Old French apaisier, "to bring to peace" (a + pais). Calm someone by giving ground.',
    'aptitude': 'From Latin aptus, "fit." Natural fitness or talent for a skill.',
    'arrogate': 'From Latin arrogare, "to claim for oneself." Seize without right.',
    'ascertain': 'From Old French acertener, "to make certain." Find out for sure through inquiry.',
    'asperity': 'From Latin asper, "rough." Harshness of tone or conditions.',
    'assuage': 'From Latin ad + suavis, "sweet/pleasant." Soften an unpleasant feeling until it eases.',
    'attenuate': 'From Latin attenuare, "to make thin." Reduce force, effect, or strength.',
    'bastion': 'From Italian bastione, a projecting fort. A stronghold defending an idea or place.',
    'belie': 'From be- + lie (untruth). Fail to give a true picture of something.',
    'belligerence': 'From Latin bellum, "war." Aggressive, warlike readiness to fight.',
    'berate': 'From be- + rate (scold). Scold angrily and at length.',
    'beseech': 'From be- + seek. Ask urgently and fervently.',
    'bolster': 'Originally a long support pillow. To bolster is to prop up or strengthen something.',
    'brevity': 'From Latin brevis, "short." Concise use of few words.',
    'brook': 'Old English brucan, "to use/enjoy," later "tolerate." Allow something unwelcome.',
    'cacophony': 'From Greek kakos (bad) + phone (sound). A harsh, discordant mix of sounds.',
    'cajole': 'From French cajoler. Persuade by coaxing and flattery rather than force.',
    'calumny': 'From Latin calumnia, "false accusation." Slander meant to damage reputation.',
    'candor': 'From Latin candor, "whiteness/brightness." Open, frank honesty in speech.',
    'castigate': 'From Latin castigare, "to correct/punish." Reprimand severely.',
    'cavort': "Likely from curvet, a horse's leap. Jump or dance about excitedly.",
    'censure': 'From Latin censura, official judgment. Strong formal disapproval.',
    'chastise': 'From Old French chastier, "to punish." Rebuke severely for wrongdoing.',
    'chicanery': 'From French chicaner, "to quibble." Trickery used for advantage.',
    'circumscribe': 'From Latin circum (around) + scribere (write). Draw a line around — limit tightly.',
    'clemency': 'From Latin clemens, "mild." Mercy, especially toward an offender.',
    'coalesce': 'From Latin co- (together) + alescere (to grow). Separate parts grow into one whole.',
    'coerce': 'From Latin coercere, "to restrain." Force compliance through pressure or threats.',
    'cohesion': 'From Latin cohaerere, "to stick together." Unity that holds a group intact.',
    'collude': 'From Latin colludere, "to play together." Cooperate secretly in wrongdoing.',
    'compendium': 'From Latin compendere, "to weigh together." A concise collected summary.',
    'complicity': 'From Latin complicare, "to fold together." Shared involvement in wrongdoing.',
    'concede': 'From Latin concedere, "to yield." Admit a point after resistance.',
    'condone': 'From Latin condonare, "to give up" a claim. Overlook or allow wrong behaviour.',
    'conjecture': 'From Latin conicere, "to throw together." A conclusion from incomplete evidence.',
    'contention': 'From Latin contendere, "to strive." Heated disagreement or a claim in debate.',
    'contingency': 'From Latin contingere, "to happen." A possible future event that is not certain.',
    'contravene': 'From Latin contra (against) + venire (come). Violate a law or agreement.',
    'corroborate': 'From Latin cor- + roborare, "to strengthen." Evidence that strengthens a claim.',
    'cupidity': 'From Latin cupiditas, desire (from Cupido). Greed for money or goods.',
    'curtail': 'From French court (short) + tail. Cut short the length or extent of something.',
    'cynicism': 'From the Cynic philosophers, who distrusted convention. Belief that motives are selfish.',
    'cynosure': 'From Greek kynosoura, "dog\'s tail" (the North Star). A centre of attention.',
    'dearth': 'From dear (costly) + -th. Scarcity that makes something precious.',
    'debilitate': 'From Latin debilis, "weak." Make someone weak or less able to function.',
    'debunk': 'From de- + bunk (nonsense). Expose a claim as false or exaggerated.',
    'deference': 'From Latin deferre, "to carry away/yield." Respectful yielding to another\'s judgment.',
    'demeanor': 'From Old French demener, "to conduct." Outward behaviour and bearing.',
    'demur': 'From Latin demorari, "to delay." Raise objections or show reluctance.',
    'deprecate': 'From Latin deprecari, "to pray against." Express strong disapproval of.',
    'deride': 'From Latin deridere, "to laugh at." Mock with contempt.',
    'desiccate': 'From Latin desiccare, "to dry out." Remove all moisture.',
    'diatribe': 'From Greek diatribe, "discourse." A bitter, forceful verbal attack.',
    'digress': 'From Latin digredi, "to step aside." Leave the main path of a topic briefly.',
    'disabuse': 'From dis- + abuse (deceive). Free someone from a false belief.',
    'discretion': 'From Latin discernere, "to separate." Careful judgement that avoids offence or harm.',
    'disparity': 'From Latin dispar, "unequal." A great difference or inequality.',
    'dispel': 'From Latin dispellere, "to drive apart." Drive away a doubt, fear, or illusion.',
    'disseminate': 'From Latin dis- + seminare, "to sow." Scatter information widely like seed.',
    'dissent': 'From Latin dis- + sentire, "to feel." Holding opinions that oppose the majority.',
    'dissonance': 'From Latin dis- + sonare, "to sound." Lack of harmony in tones or ideas.',
    'divulge': 'From Latin divulgare, "to publish among the people." Reveal private information.',
    'doctrine': 'From Latin doctrina, "teaching." A taught set of beliefs held by a group.',
    'educe': 'From Latin educere, "to lead out." Draw out something latent or potential.',
    'efface': 'From French effacer, "to wipe out." Erase marks or make oneself unnoticed.',
    'effrontery': 'From Latin effrons, "shameless." Insolent, barefaced boldness.',
    'elicit': 'From Latin elicere, "to draw out." Draw forth a response or reaction.',
    'eloquence': 'From Latin eloquentia, speaking out. Fluent, persuasive use of language.',
    'embellish': 'From French embellir, "to make beautiful." Add decorative (or invented) detail.',
    'emulate': 'From Latin aemulari, "to rival." Match or surpass by careful imitation.',
    'encomium': 'From Greek enkomion, a festival praise. Formal high praise in speech or writing.',
    'encumber': 'From Old French encombrer, "to block." Burden so free action is hindered.',
    'enigma': 'From Greek ainigma, "riddle." A person or thing that is hard to understand.',
    'enjoin': 'From Latin injungere, "to join to/impose." Formally instruct or urge action.',
    'enumerate': 'From Latin enumerare, "to count out." List items one by one.',
    'equanimity': 'From Latin aequus (even) + animus (mind). Calm composure under stress.',
    'espouse': 'From Latin sponsare, "to betroth." Adopt or support a cause as one\'s own.',
    'eulogy': 'From Greek eu (well) + logos (speech). A speech of high praise, often for the dead.',
    'exacerbate': 'From Latin exacerbare, "to make harsh." Make a bad situation worse.',
    'exculpate': 'From Latin ex- + culpa, "fault." Clear of blame or guilt.',
    'exigency': 'From Latin exigere, "to demand." An urgent need or pressing crisis.',
    'expatiate': 'From Latin expatiari, "to wander." Speak or write at length on a topic.',
    'expiate': 'From Latin expiare, "to atone." Make amends for wrongdoing.',
    'extirpate': 'From Latin exstirpare, "to root out." Destroy completely at the root.',
    'extol': 'From Latin extollere, "to raise up." Praise highly and enthusiastically.',
    'extricate': 'From Latin ex- + tricae, "perplexities." Free from a tangle or difficulty.',
    'facilitate': 'From Latin facilis, "easy." Make a process easier to do.',
    'fallacy': 'From Latin fallacia, "deception." A mistaken belief from unsound reasoning.',
    'falter': 'Related to faltere, "to be unsteady." Lose strength, confidence, or smooth motion.',
    'foment': 'From Latin fomentum, a warm poultice. Metaphorically, stir up trouble or unrest.',
    'foresight': 'Fore + sight. The ability to see ahead and prepare wisely.',
    'forestall': 'From fore- + stall (intercept). Act first to prevent an expected event.',
    'fortitude': 'From Latin fortis, "strong." Courage and strength of mind in adversity.',
    'fulcrum': 'From Latin fulcire, "to prop." The pivot point of a lever — a central support.',
    'gainsay': 'From gain- (against) + say. Deny or contradict openly.',
    'garrulity': 'From Latin garrire, "to chatter." Excessive trivial talkativeness.',
    'hegemony': 'From Greek hegemonia, "leadership." Dominance of one group over others.',
    'hierarchy': 'From Greek hieros (sacred) + arkhein (to rule). A ranked system of levels.',
    'hypocrisy': 'From Greek hypokrisis, "acting a part." Claiming virtues one\'s acts deny.',
    'iconoclast': 'From Greek eikon (image) + klan (to break). Attacker of cherished beliefs.',
    'idiosyncrasy': "From Greek idios (one's own) + synkrasis (mixture). A personal peculiar habit.",
    'ignominy': 'From Latin in- + nomen, "name." Public shame that stains one\'s name.',
    'impede': 'From Latin impedire, "to shackle the feet." Block or slow progress.',
    'impetuosity': 'From Latin impetus, "assault." Acting with rash, unthinking force.',
    'impetus': 'From Latin impetere, "to attack/assail." A driving force that sets things moving.',
    'implore': 'From Latin implorare, "to invoke with tears." Beg earnestly for help.',
    'impute': 'From Latin imputare, "to reckon to." Attribute a fault or quality to someone.',
    'incite': 'From Latin incitare, "to set in motion." Urge others toward (often violent) action.',
    'inculcate': 'From Latin inculcare, "to tread in." Instill by persistent teaching.',
    'indict': 'From Latin indictare, "to declare." Formally charge with a crime.',
    'indictment': 'From Latin indictare, "to declare." A formal charge of a serious crime.',
    'inertia': 'From Latin iners, "idle." Tendency to stay still or unchanged.',
    'inference': 'From Latin inferre, "to bring in." A conclusion drawn from evidence and reasoning.',
    'ingenuity': 'From Latin ingenium, "natural capacity." Clever inventiveness.',
    'instigate': 'From Latin instigare, "to urge on." Bring about an action, often a bad one.',
    'insularity': 'From Latin insula, "island." Narrowness from isolation — cultural isolation.',
    'interdict': 'From Latin interdicere, "to forbid." Prohibit by official authority.',
    'interlocutor': 'From Latin interloqui, "to speak between." A participant in a dialogue.',
    'invective': 'From Latin invehi, "to attack." Abusive, highly critical language.',
    'inveigh': 'From Latin invehi, "to attack with words." Speak with hostile force against.',
    'inveigle': 'From Old French aveugler, "to blind." Entice by deception or flattery.',
    'jurisdiction': 'From Latin jus (law) + dicere (to say). Official power to decide legal matters.',
    'lambaste': 'From lam + baste (beat). Criticize harshly and at length.',
    'litany': 'From Greek litaneia, "prayer." A long repetitive series of items or complaints.',
    'maelstrom': 'From Dutch malen (grind) + stroom (stream). A violent whirlpool or turmoil.',
    'malice': 'From Latin malitia, "badness." Desire to do harm or evil.',
    'maxim': 'From Latin maxima (propositio), "greatest premise." A short general rule of conduct.',
    'mediocrity': 'From Latin mediocris, "middling." The quality of being merely average.',
    'miasma': 'From Greek miasma, "pollution." An unhealthy or oppressive atmosphere.',
    'notoriety': 'From Latin notus, "known." Fame for something bad.',
    'nuance': 'From French nuer, "to shade." A subtle difference in meaning or tone.',
    'nullify': 'From Latin nullus, "none." Make something legally void — of no force.',
    'obviate': 'From Latin obviare, "to meet/prevent." Remove a difficulty in advance.',
    'opprobrium': 'From Latin opprobrum, "reproach." Public disgrace after bad conduct.',
    'ordeal': 'From Old English ordal, a trial by ordeal. A prolonged painful test of endurance.',
    'oscillate': 'From Latin oscillare, "to swing." Move back and forth regularly.',
    'palliate': 'From Latin palliare, "to cloak." Ease symptoms without curing the cause.',
    'panegyric': 'From Greek panegyrikos, of a public assembly. Formal public praise.',
    'paradox': 'From Greek para (beyond) + doxa (opinion). A seeming contradiction that may be true.',
    'paragon': 'From Italian paragone, "touchstone." A perfect model of a quality.',
    'paroxysm': 'From Greek paroxynein, "to sharpen." A sudden violent outburst of feeling.',
    'penury': 'From Latin penuria, "need/want." Extreme poverty.',
    'perfidy': 'From Latin perfidia, "faithlessness." Treacherous breach of trust.',
    'perjure': 'From Latin perjurare, "to swear falsely." Lie under legal oath.',
    'placate': 'From Latin placare, "to calm." Make someone less angry or hostile.',
    'plethora': 'From Greek plethein, "to be full." An excessive amount of something.',
    'predicament': 'From Latin praedicare, "to declare." A difficult or embarrassing situation.',
    'premise': 'From Latin praemittere, "to send before." A statement that supports a conclusion.',
    'prestige': 'From Latin praestigium, "illusion," later "reputation." Widespread respect for achievement.',
    'probity': 'From Latin probitas, "goodness." Proven honesty and strong moral principle.',
    'proclivity': 'From Latin proclivis, "sloping forward." A habitual tendency, often toward something bad.',
    'prodigality': 'From Latin prodigus, "wasteful." Reckless, lavish waste of resources.',
    'prognosticate': 'From Greek prognosis, "foreknowledge." Foretell from present signs.',
    'propensity': 'From Latin propendere, "to hang forward." A natural inclination toward a behaviour.',
    'proscribe': 'From Latin proscribere, "to publish as outlawed." Forbid by law.',
    'quagmire': 'Quag (bog) + mire. A soft bog — or a sticky hazardous situation.',
    'ramification': 'From Latin ramus, "branch." A complex branching consequence of an action.',
    'rancor': 'From Latin rancere, "to stink/be rank." Long-standing bitter resentment.',
    'ravage': 'From French ravir, "to seize." Cause severe widespread destruction.',
    'recrimination': 'From Latin re- + criminare, "to accuse." A counter-accusation in reply.',
    'reiterate': 'From Latin reiterare, "to repeat." Say again for emphasis.',
    'relinquish': 'From Latin relinquere, "to leave behind." Voluntarily give up a claim or hold.',
    'reprobate': 'From Latin reprobare, "to reject." An unprincipled person beyond moral reform.',
    'repudiate': 'From Latin repudiare, "to cast off." Refuse to accept or be associated with.',
    'revere': 'From Latin vereri, "to fear/respect." Feel deep respectful admiration.',
    'rhetoric': 'From Greek rhetorike, the art of the orator. Persuasive speaking and writing.',
    'sagacity': 'From Latin sagax, "wise/keen." Keen practical wisdom.',
    'sanction': 'From Latin sancire, "to make sacred/decree." A penalty for breach — or official approval.',
    'scintilla': 'From Latin scintilla, "spark." A tiny trace or spark of a quality.',
    'scrutinize': 'From Latin scrutari, "to search" (even refuse). Examine closely and carefully.',
    'solipsism': 'From Latin solus (alone) + ipse (self). The view that only the self is certain.',
    'sophistry': 'From the Greek Sophists. Clever but fallacious reasoning meant to deceive.',
    'spate': 'Originally a flood of water. A sudden large series of similar events.',
    'speciousness': 'From Latin speciosus, "showy." Apparent truth that is actually false.',
    'stigma': 'From Greek stigma, "mark" or brand. A mark of disgrace or social shame.',
    'stultify': 'From Latin stultus, "foolish." Make someone feel useless or drained of initiative.',
    'suborn': 'From Latin subornare, "to equip secretly." Bribe someone into unlawful acts.',
    'substantiate': 'From Latin substantia, "substance." Give solid substance (proof) to a claim.',
    'supersede': 'From Latin supersedere, "to sit above." Replace something older or inferior.',
    'surfeit': 'From Old French surfaire, "to overdo." Excess that produces disgust.',
    'sycophancy': 'From Greek sykophantes, a false accuser. Obsequious flattery for gain.',
    'tautology': 'From Greek tauto (the same) + logos. Needless repetition that adds no new content.',
    'temerity': 'From Latin temere, "rashly." Reckless boldness.',
    'transgress': 'From Latin transgredi, "to step across." Cross a moral or legal boundary.',
    'truncate': 'From Latin truncare, "to maim/cut." Shorten by cutting off an end.',
    'turpitude': 'From Latin turpis, "base/ugly." Wicked or depraved conduct.',
    'umbrage': 'From Latin umbra, "shadow." Offence taken as if cast into shade.',
    'undermine': 'Literally dig under a foundation. Weaken gradually, often in secret.',
    'upbraid': 'From Old English upbregdan, "to bring up as a fault." Scold severely.',
    'verisimilitude': 'From Latin verum (truth) + similis (like). The appearance of being true or real.',
    'vicissitude': 'From Latin vicis, "change/turn." An unwelcome change of fortune.',
    'vindicate': 'From Latin vindicare, "to claim/avenge." Clear of blame with proof.',
    'vitiate': 'From Latin vitiare, "to spoil." Impair quality or validity.',
    'volition': 'From Latin volo, "I wish." The power of using one\'s own will.',
    'welter': 'From Middle Dutch welteren, "to roll." Toss in turmoil or lie soaked in something.',
    'zealot': 'From Greek zelotes, "emulator." A fanatical, uncompromising partisan.',
}
