#!/bin/bash
set -e

echo "=== makuharistudio portfolio build ==="

PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"
SOURCE="$PROJECT_ROOT/source"
DIST="$PROJECT_ROOT/dist"

echo "Creating output directories..."
rm -rf "$DIST/js" "$DIST/assets" "$DIST/themes"
mkdir -p "$DIST" "$SOURCE/library"

echo "Generating catalog (build-time index)..."

cat > "$SOURCE/library/catalog.ts" << EOF
// Auto-generated by build.sh — DO NOT EDIT
export const catalog = {
  posts: [
$(cd "$SOURCE/markdown/posts" 2>/dev/null && ls -1 *.md | sort -r | sed 's/^/    "/;s/$/",/')
  ],
  projects: [
$(cd "$SOURCE/markdown/projects" 2>/dev/null && ls -1 *.md | sort -r | sed 's/^/    "/;s/$/",/')
  ],
  readings: [
$(cd "$SOURCE/markdown/readings" 2>/dev/null && ls -1 *.md | sort -r | sed 's/^/    "/;s/$/",/')
  ],
  games: [
$(cd "$SOURCE/games" 2>/dev/null && ls -1 *.ts *.tsx 2>/dev/null | sed 's/\.tsx\?$//' | grep -E '^(DualNBack|RocketLaunchSimulation|SatelliteCoverageOptimiser|VocabularyTrainer)$' | sed 's/^/    "/;s/$/",/' || true)
  ]
} as const;

export type ContentType = keyof typeof catalog;
EOF

echo "Catalog generated."

echo "Generating markdown raw loaders..."
python3 - << 'PY'
from pathlib import Path
root = Path("source/markdown")
lines = [
    "// Auto-generated by build.sh — DO NOT EDIT",
    "// esbuild --loader:.md=text turns each import into the file contents.",
    "// @ts-nocheck",
    "export const rawFiles: Record<string, string> = {",
]
for kind in ("posts", "projects", "readings"):
    folder = root / kind
    for path in sorted(folder.glob("*.md"), reverse=True):
        key = f"{kind}/{path.name}"
        ident = f"{kind}_{path.stem.replace('-', '_')}"
        lines.append(f"  '{key}': {ident},")
lines.append("};")
lines.append("")
for kind in ("posts", "projects", "readings"):
    folder = root / kind
    for path in sorted(folder.glob("*.md"), reverse=True):
        ident = f"{kind}_{path.stem.replace('-', '_')}"
        rel = f"../markdown/{kind}/{path.name}"
        lines.append(f"import {ident} from '{rel}';")
Path("source/library/markdown-raw.ts").write_text("\n".join(lines) + "\n")
print(f"wrote {len(lines)} lines")
PY

if ! command -v tsc >/dev/null 2>&1; then
  echo "ERROR: tsc not found. Run: sudo dnf install -y typescript"
  exit 1
fi

if ! command -v esbuild >/dev/null 2>&1; then
  echo "ERROR: esbuild not found."
  exit 1
fi

echo "Type checking with tsc..."
tsc --noEmit --pretty false
echo "Type checking passed."

echo "Bundling with esbuild..."
esbuild source/main.ts \
  --bundle \
  --outfile=dist/js/main.js \
  --format=esm \
  --target=es2022 \
  --loader:.md=text \
  --log-level=warning

echo "Copying static assets..."
mkdir -p "$DIST/assets" "$DIST/themes" "$DIST/assets/games"
cp -a "$SOURCE/assets/." "$DIST/assets/"
# Game card photos sit beside the modules. Copy only the images.
find "$SOURCE/games" -maxdepth 1 -type f \( -name '*.png' -o -name '*.jpg' -o -name '*.gif' -o -name '*.webp' \) -exec cp -a {} "$DIST/assets/games/" \;
# Theme folders keep their light/dark contract. CSS stays next to its accent
# and background images so relative urls resolve without a rewrite.
cp -a "$SOURCE/themes/." "$DIST/themes/"
# Theme CSS is bundled into dist/js by esbuild. Copy panel CSS companion assets
# only if a future theme ships files next to the stylesheet.
if [ -f "$SOURCE/assets/robots.txt" ]; then
  cp "$SOURCE/assets/robots.txt" "$DIST/robots.txt"
fi

echo "Copying index.html..."
cp "$PROJECT_ROOT/index.html" "$DIST/"

echo ""
echo "Build completed successfully!"
echo "Output: $DIST"
echo ""
echo "To test locally, run:"
echo "    python3 -m http.server 8000 --directory dist"
echo "Then open http://localhost:8000"
